force-app/main/default/objects/Codey_Obj__c/Codey_Obj__c.object-meta.xml
<CustomObject>
    <description>Example object for Demo</description>
    <label>Codey Obj</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Codey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Codey Objs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Codey_Obj__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>field1__c</fullName>
    <description>Example field 1</description>
    <inlineHelpText>Example field1</inlineHelpText>
    <label>Field 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Codey_Obj__c/fields/Field2__c.field-meta.xml
<CustomField>
    <fullName>field2__c</fullName>
    <description>Example field 2</description>
    <inlineHelpText>Example field2</inlineHelpText>
    <label>Field 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CodeyFeature.cls
public with sharing class CodeyFeature {

    public void invoke(String someStr) {
        Codey_Obj__c obj = createCodeyObj(someStr);

        // further steps to create request
        RequestHandler handler = new RequestHandler();
        CodeyRequest request = handler.createRequest(obj);
        handler.post(request);
    }
    
    Codey_Obj__c createSimpleObj(String someStr) {
        Codey_Obj__c obj = new Codey_Obj__c(Field1__c = someStr);
        return obj;
    }

    Codey_Obj__c createCodeyObj(String someStr) {
        Codey_Obj__c obj = new Codey_Obj__c();
        obj.field1__c = doubleInput(someStr.length());
        obj.field2__c = doubleString(someStr);
        return obj;
    }

    private String doubleInput(Integer input) {
        return '' + (input * 2);
    }

    private String doubleString(String input) {
        return input + input;
    }

}